#!/bin/bash

API_URL= "https://pokeapi.co/api/v2/pokemon/"
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

echo "feching Data from the Pokermon API"

curl -s -o "$OUTPUT_FILE" "$API_URL" 2> /tmp/curl_error.txt

if [ $? -eq 0 ]; then
 ecoh "✓ Success! Data saved to $OUTPUT_FILE"
 ecoh "You can view it with: jq . < $OUTPUT_FILE | head -n 50"

else
 timestamp=$(date '+%Y-%m-%d %H:%M:%S')
 error_msg="[$timestamp] Failed to fetch data from $API_URL"
 echo "$error_msg" >> "$ERROR_FILE"
 cat /tmp/curl_error.txt >> "$ERROR_FILE"
 echo "" >> "$ERROR_FILE"
 echo "✗ Error: Request failed"
 echo "Error logged to $ERROR_FILE"
 exit 1
fi
